# Generated by Django 5.2.14 on 2026-08-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_employee_late_alerts_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Первый выходной день')),
                ('end_date', models.DateField(verbose_name='Последний выходной день')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='attendance.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Выходной сотрудника',
                'verbose_name_plural': 'Выходные сотрудников',
                'ordering': ['start_date', 'employee__full_name'],
            },
        ),
    ]
